<a href="https://colab.research.google.com/github/FlashPCR/01_numpy_intro/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.2, 2.5, 1.7])
print(x)

[1.2 2.5 1.7]


In [ ]:
x.dtype

dtype('float64')

2D Array

In [ ]:
x = np.array([[1, 2],[-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([[1, 2, 3], [4, 2, 8]])
print(x)

[[1 2 3]
 [4 2 8]]


In [ ]:
x.shape

(2, 3)

3D Array

In [ ]:
x = np.array(
    [[[4, 2, 3],
      [3, 8, 9]],

    [[4, 3, 5],
       [5, 5, 6]],
     [[4, 4, 5],
      [5, 6, 7]]]
)
x

array([[[4, 2, 3],
        [3, 8, 9]],

       [[4, 3, 5],
        [5, 5, 6]],

       [[4, 4, 5],
        [5, 6, 7]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(3, 2, 3)